### ISSUE TITLE
model_type key not exists or unsupported value

### ISSUE THREAD

**Issue by rickywu** [modelscope/dash-infer#16]
run with https://huggingface.co/THUDM/glm-4-9b-chat-1m

config file
```
{
    "model_name": "glm-4-9b-chat-1m",
    "model_type": "ChatGLM_v4",
    "model_path": "/data/glm-4-9b-chat-1m/",
    "data_type": "float32",
    "device_type": "CPU",
    "device_ids": [
        0
    ],
    "multinode_mode": false,
    "engine_config": {
        "engine_max_length": 8192,
        "engine_max_batch": 8,
        "do_profiling": false,
        "num_threads": 0,
        "matmul_precision": "medium"
    },
    "generation_config": {
        "temperature": 0.9,
        "early_stopping": true,
        "top_k": 1024,
        "top_p": 0.7,
        "repetition_penalty": 1.0,
        "presence_penalty": 0.0,
        "min_length": 0,
        "max_length": 8192,
        "no_repeat_ngram_size": 0,
        "eos_token_id": 2,
        "seed": 1234,
        "stop_words_ids": [
            [
                151329
            ],
            [
                151336
            ],
            [
                151338
            ]
        ]
    },
    "convert_config": {
        "do_dynamic_quantize_convert": false
    },
    "quantization_config": {
        "activation_type": "bfloat16",
        "weight_type": "uint8",
        "SubChannel": true,
        "GroupSize": 512
    }
}

```

got error:
```
Traceback (most recent call last):
  File "/mnt/d/Work/dash-infer/examples/python/0_basic/basic_example_chatglm4.py", line 131, in <module>
    engine_helper = EngineHelper(config)
  File "/opt/miniconda3/envs/dashinfer/lib/python3.10/site-packages/dashinfer/helper/helper.py", line 27, in __init__
    config = ConfigManager.create_config(user_config)
  File "/opt/miniconda3/envs/dashinfer/lib/python3.10/site-packages/dashinfer/helper/helper.py", line 635, in create_config
    ConfigManager.check_config(config)
  File "/opt/miniconda3/envs/dashinfer/lib/python3.10/site-packages/dashinfer/helper/helper.py", line 627, in check_config
    raise ValueError("config['{}']: key not exists or unsupported value".format(key))
ValueError: config['model_type']: key not exists or unsupported value

```

**Comment by rickywu** [comment]
change to v3 can startup
